spring:
  application:
    name: utility-service

  datasource:
    url: jdbc:postgresql://139.59.53.120:5433/postgres?currentSchema=prepost&options=-c%20TimeZone=Asia/Yangon
    username: postgres
    password: Adm1n
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc.batch_size: 200
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
    open-in-view: false
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

spring-batch:
  chunk-size: 2000

garage:
  access_key: "GKdc6549790849c5c032798435"
  secret_key: "c4bc9b09f358164cb213bbb9694074a2b79bd742283dca6184eb19d7eb249ff4"
  host: 139.59.53.120
  port: 3900
  bucket: "sit-mpay"
  electricitybill_dir: "electricitybill"

storage:
  local-temp-path: ${TEMP_PATH:./batch-temp}